name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: elixir
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          
      # The following steps only run if a release PR was merged
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '26.0'
        if: ${{ steps.release.outputs.release_created }}
          
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Install dependencies
        run: mix deps.get
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Generate docs
        run: mix docs
        if: ${{ steps.release.outputs.release_created }} 